//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopsProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class shop
    {
        public shop()
        {
            this.UserShop = new HashSet<UserShop>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string imagePath { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public Nullable<decimal> latitude { get; set; }
        [NotMapped]
        public double distance { get; set; }
    
        public virtual ICollection<UserShop> UserShop { get; set; }
    }
}
