//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopsProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop
    {
        public int id { get; set; }
        public Nullable<int> userId { get; set; }
        public string name { get; set; }
        public Nullable<decimal> distance { get; set; }
        public string imagePath { get; set; }
        public Nullable<bool> isPreferred { get; set; }
        public Nullable<bool> isDisliked { get; set; }
    
        public virtual login login { get; set; }
    }
}
