//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopsProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserShop
    {
        public int login_id { get; set; }
        public int shop_id { get; set; }
        public Nullable<System.DateTime> likedDate { get; set; }
        public Nullable<System.DateTime> dislikedDate { get; set; }
        public Nullable<bool> isPreferred { get; set; }
        public Nullable<bool> isDisliked { get; set; }
    
        public virtual login login { get; set; }
        public virtual shop shop { get; set; }
    }
}
